a = int(input('Digite um primeiro número: '))
b = int(input('Digite um segundo número: '))
c = int(input('Digite um terceiro número: '))
print('Aqui está os antecessores dos números')
aa = a-1
print('O antecessor do número',a,'é o número',aa)
ab = b-1
print('O antecessor do número',b,'é o número',ab)
ac = c-1
print('O antecessor do número',c,'é o número',ac)
print('Aqui está os sucessores dos números')
sa = a+1
print('O sucessor do número',a,'é o número',sa)
sb = b+1
print('O sucessor do número',b,'é o número',sb)
sc = c+1
print('O sucessor do número',c,'é o número',sc)

